# Generated by Django 4.2.6 on 2024-03-10 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article_app', '0001_initial'),
        ('comments_app', '0002_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article_app.article'),
        ),
    ]
