# Generated by Django 4.2.6 on 2023-10-31 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('most_liked_articles_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='most_liked_articles_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='commentId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='most_liked_articles_app.comment'),
        ),
    ]
