# Generated by Django 4.2.6 on 2023-11-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default=None, max_length=254)),
                ('password', models.CharField(default=None)),
                ('photo', models.ImageField(blank=True, default=None, null=True, upload_to='')),
                ('bio', models.CharField(blank=True, default=None, max_length=2000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
