# Generated by Django 4.2.6 on 2023-12-02 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='photo',
            new_name='image',
        ),
    ]
