# Generated by Django 4.2.6 on 2023-12-16 19:39

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='null', editable=False, populate_from='name'),
            preserve_default=False,
        ),
    ]
