# Generated by Django 4.2.6 on 2024-03-04 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0003_user_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='bio',
            new_name='description',
        ),
    ]
