# Generated by Django 4.2.6 on 2024-03-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_app', '0004_rename_bio_user_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(default='default', max_length=2000),
            preserve_default=False,
        ),
    ]
