# Generated by Django 4.2.6 on 2023-10-31 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('creativesparkapp', '0003_article_readtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='readTime',
            new_name='read_time',
        ),
        migrations.RemoveField(
            model_name='article',
            name='commentId',
        ),
        migrations.AddField(
            model_name='article',
            name='claps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='comment',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='creativesparkapp.comment'),
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='comment',
            name='claps',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='content',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=None, max_length=2000),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
