# Generated by Django 4.2.6 on 2023-11-19 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_signup_app', '0001_initial'),
        ('all_articles_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='login_signup_app.user'),
        ),
    ]
