# Generated by Django 4.2.6 on 2024-03-09 17:31

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_articles_app', '0002_article_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='empty', editable=False, populate_from='title'),
            preserve_default=False,
        ),
    ]
