# Generated by Django 4.2.6 on 2024-03-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_articles_app', '0003_article_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
    ]
