# Generated by Django 4.2.6 on 2023-12-02 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('all_articles_app', '0003_article_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='image',
        ),
    ]
