# Generated by Django 4.2.6 on 2024-03-10 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_app', '0003_alter_comment_article'),
        ('all_articles_app', '0004_remove_article_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
