# Generated by Django 4.2.6 on 2023-12-02 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_articles_app', '0004_remove_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=''),
        ),
    ]
