# Generated by Django 4.2.6 on 2023-12-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_articles_app', '0005_article_author_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_image',
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(default='null', upload_to='article_images/'),
            preserve_default=False,
        ),
    ]
