# Generated by Django 4.2.6 on 2023-12-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_articles_app', '0006_remove_article_author_image_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='topic',
            field=models.CharField(default='Life', max_length=100),
        ),
    ]
