# Generated by Django 4.2.6 on 2023-12-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_articles_app', '0007_article_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='topic',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
