"""Add article metadata fields

Revision ID: 6526af409a52
Revises: cc8fdf261790
Create Date: 2026-08-03 23:53:10.082901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6526af409a52'
down_revision = 'cc8fdf261790'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topic', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('claps', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('read_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('read_time')
        batch_op.drop_column('claps')
        batch_op.drop_column('topic')

    # ### end Alembic commands ###
