"""Create categories table

Revision ID: 795d16ec0b89
Revises: fb91b92a1b6a
Create Date: 2026-07-30 23:37:18.466801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '795d16ec0b89'
down_revision = 'fb91b92a1b6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
